spring:
    profiles: test
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
name: test-YAML
environment: test
servers: 
    - www.abc.test.com
    - www.xyz.test.com